### PR TITLE
doc: adding debug

### PR DESCRIPTION
**Pull request by RodrigoMNardi**

### CODE REVIEW

**Comment by RodrigoMNardi** [comment]
ci:rerun 90f1e4e01781ffdba13a65577329e6380d96cee5

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by qlyoung** [comment]
I'd like to request that the bot not even comment about reruns - even that is noisier than needed. Just the +1 react on the message is sufficient, and since a major benefit of this work is reducing non-human content in pull requests, I think it's better to skip the message.

Super excited for this work to come to fruition by the way!

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
> I'd like to request that the bot not even comment about reruns - even that is noisier than needed. Just the +1 react on the message is sufficient, and since a major benefit of this work is reducing non-human content in pull requests, I think it's better to skip the message.
> 
> Super excited for this work to come to fruition by the way!

Sure. I will remove the bot feedback.

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by RodrigoMNardi** [comment]
> I'd like to request that the bot not even comment about reruns - even that is noisier than needed. Just the +1 react on the message is sufficient, and since a major benefit of this work is reducing non-human content in pull requests, I think it's better to skip the message.
> 
> Super excited for this work to come to fruition by the way!

Done.

**Comment by RodrigoMNardi** [comment]
ci:rerun 9b785c7

**Comment by qlyoung** [comment]
Thank you very much! Again I'm super excited for this to land, it'll make reviewing PRs so much more pleasant.

**Comment by RodrigoMNardi** [comment]
> Thank you very much! Again I'm super excited for this to land, it'll make reviewing PRs so much more pleasant.

This is to make life easier.

**Comment by RodrigoMNardi** [comment]
ci:rerun

**Comment by RodrigoMNardi** [comment]
ci:rerun

**Comment by RodrigoMNardi** [comment]
ci:rerun

**Pull request closed without merging**
